public class TestClass2 {
    Public static void test(){
        String test='Learn in-demand Checkers I am developer from skills for free to drive your company and career forward. Anyone can get hands-on experience building intuitive AI agents that handle everyday tasks, enhance the customer experience, and create business impact. Be an Agentblazer and transform how work gets done';
               test+='Agentforce is what AI was meant to be. It goes beyond chatbots and copilots. Agentforce executes end-to-end tasks to scale work across all business functions, like resolving customer cases or qualifying sales leads. And companies need Agentblazers who can leverage the power of AI to make their visions a reality. With Trailhead, you can learn to build customizable autonomous agents and create a digital workforce across any role, any industry, or any use case.';
         String output=UseCase2.m1(test);
        System.debug(output);
    }
}