name: Based on the inputs Artifacts Generation 

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Name of the branch'
        required: true
        default: 'test'

      diff:
        description: 'Make the artifact from commit to commit'
        # required: true
        default: 'false'

      overall:
        description: 'Make the artifact based on the branch'
        #required: true
        default: 'false'

      fromCommit:
        description: 'From which commit to start to make the artifacts'
        required: false
        default: ''

      toCommit:
        description: 'To which commit to make the artifact'
        required: false
        default: ''

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check the variables and set
        id: setvars
        run: |
          echo "Branch: ${{ github.event.inputs.branch }}"
          echo "Diff: ${{ github.event.inputs.diff }}"
          echo "Overall: ${{ github.event.inputs.overall }}"
          echo "From commit: ${{ github.event.inputs.fromCommit }}"
          echo "To commit: ${{ github.event.inputs.toCommit }}"
          # Check that both diff and overall are not true at the same time
          if [[ "${{ github.event.inputs.diff }}" == "true" && "${{ github.event.inputs.overall }}" == "true" ]]; then
            echo "Both diff and overall cannot be true at the same time"
            exit 1
          fi

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Install Salesforce Scanner Plugin
        run: sf plugins install @salesforce/sfdx-scanner

      # which branch you provide that repo you will get 
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0 

      # Run Diff Scan
      - name: Run Diff Scan
        if: ${{ github.event.inputs.diff == 'true' }}
        run: |
          echo "Running SCA on changed files between from commit and TOcommits"
          git fetch origin ${{ github.event.inputs.branch }}

          CHANGED_FILES=$(git diff --name-only \
            ${{ github.event.inputs.fromCommit }} \
            ${{ github.event.inputs.toCommit }} \
            | grep -E '\.(cls|js)$' || true)

          echo "Changed files: $CHANGED_FILES"
          mkdir -p reports

          if [ -n "$CHANGED_FILES" ]; then
            sf scanner:run \
              --format json \
              --target "$CHANGED_FILES" \
              --category "Design,Best Practices,Performance" \
              --outfile reports/scanner-diff.json || true
          else
            echo "[]" > reports/scanner-diff.json
          fi

      # Run Overall Scan
      - name: Run Overall Scan
        if: ${{ github.event.inputs.overall == 'true' }}
        run: |
          echo "Running SCA on entire branch..."
          mkdir -p reports
          sf scanner:run \
            --format json \
            --target "force-app/**/*.cls,force-app/**/*.js" \
            --category "Design,Best Practices,Performance" \
            --outfile reports/scanner-overall.json || true

      #  reports
      - name: Upload Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: sca-scan-report
          path: reports/*.json
