name: Validate Production Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'force-app/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Java (required for PMD)
      - name: Setup Java (required for PMD)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Download PMD
      - name: Download PMD
        run: |
          curl -L -o pmd.zip https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.55.0/pmd-bin-6.55.0.zip
          unzip pmd.zip

      # Step 4: Run PMD - show text output in logs AND save HTML report
      - name: Run PMD Analysis
        run: |
          mkdir -p reports

          echo "▶ Running PMD (text output for GitHub logs)..."
          ./pmd-bin-6.55.0/bin/run.sh pmd \
            -d force-app/main/default/classes \
            -R force-app/main/default/classes/apex-ruleset.xml \
            -f text

          echo "▶ Generating PMD HTML report..."
          ./pmd-bin-6.55.0/bin/run.sh pmd \
            -d force-app/main/default/classes \
            -R force-app/main/default/classes/apex-ruleset.xml \
            -f html \
            -r reports/pmd-report.html

      # Step 5: Upload PMD Report as GitHub Artifact
      - name: Upload PMD Report
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: reports/pmd-report.html

      # Step 6: Validate against Salesforce Org (Dry Run)
      - name: Authenticate to Org
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > auth.txt
          sfdx auth:sfdxurl:store -f auth.txt -a MyOrg

      - name: Validate Deployment to Salesforce Org
        run: |
          echo "▶ Starting dry-run deployment to Salesforce..."
          sfdx force:source:deploy \
            -p force-app \
            --checkonly \
            --targetusername MyOrg \
            --testlevel NoTestRun \
            --json > deploy-result.json

      - name: Show Deployment Errors (if any)
        run: |
          cat deploy-result.json
          if grep -q '"status": 1' deploy-result.json; then
            echo "❌ Deployment validation failed. Check logs above for details."
            exit 1
          else
            echo "✅ Apex validation passed."
          fi
