name: Validate Production Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'force-app/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Changed Apex/JS Files
        id: changes 
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} HEAD \
            | grep -E '^force-app/.*\.(cls|js)$' || true)

          echo "Changed files:"
          echo "$CHANGED_FILES" 

          {
            echo "files<<EOF"
            echo "$CHANGED_FILES"
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Setup Java (required for PMD)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Install Salesforce Scanner Plugin
        run: sf plugins install @salesforce/sfdx-scanner

      - name: Run Diff & Overall Scans (Separate ZIPs)
        run: |
          mkdir -p reports
          
          # Run diff scan (only if changed files exist)
          if [ -n "${{ steps.changes.outputs.files }}" ]; then
            sf scanner:run \
              --format json \
              --target "${{ steps.changes.outputs.files }}" \
              --category "Design,Best Practices,Performance" \
              --outfile reports/scanner-diff.json || true
          else
            echo "[]" > reports/scanner-diff.json
          fi
          
          # Run overall scan
          sf scanner:run \
            --format json \
            --target "force-app" \
            --category "Design,Best Practices,Performance" \
            --outfile reports/scanner-overall.json || true
          
          # Zip separately
          cd reports
          zip sca-diff.zip scanner-diff.json
          zip sca-overall.zip scanner-overall.json
          cd ..

      - name: Upload Diff SCA Report
        uses: actions/upload-artifact@v4
        with:
          name: sca-diff
          path: reports/sca-diff.zip

      - name: Upload Overall SCA Report
        uses: actions/upload-artifact@v4
        with:
          name: sca-overall
          path: reports/sca-overall.zip
