name: Validate Production Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'force-app/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Java for PMD
      - name: Setup Java (required for PMD)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Download PMD
      - name: Download PMD
        run: |
          curl -L -o pmd.zip https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.55.0/pmd-bin-6.55.0.zip
          unzip pmd.zip

      # Run PMD analysis (remove `|| true` so it fails the PR if issues are found)
      - name: Run PMD Analysis
        run: |
          mkdir -p reports
          ./pmd-bin-6.55.0/bin/run.sh pmd \
            -d force-app/main/default/classes \
            -R force-app/main/default/classes/apex-ruleset.xml \
            -f html \
            -r reports/pmd-report.html

      # Upload PMD report as GitHub artifact
      - name: Upload PMD Report
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: reports/pmd-report.html

      # Authenticate to Salesforce Org using SFDX URL
      - name: Authenticate to Org
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > auth.txt
          sfdx auth:sfdxurl:store -f auth.txt -a MyOrg

      # Validate deployment using dry run and export JSON result
      - name: Validate (Dry Run) Deploy to Org
        run: |
          sfdx force:source:deploy \
            -p force-app \
            --checkonly \
            --targetusername MyOrg \
            --testlevel NoTestRun \
            --json > deploy-result.json

      # Show validation result and fail if any errors
      - name: Show Deployment Errors (if any)
        run: |
          cat deploy-result.json
          if grep -q '"status": 1' deploy-result.json; then
            echo " Apex validation failed. See above errors."
            exit 1
          else
            echo " Apex validation passed."
          fi
