name: Validate on Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'force-app/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java (for PMD)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download PMD
        run: |
          curl -L -o pmd.zip https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.55.0/pmd-bin-6.55.0.zip
          unzip pmd.zip

      - name: Run PMD Analysis
        run: |
          mkdir -p reports
          ./pmd-bin-6.55.0/bin/run.sh pmd \
            -d force-app/main/default/classes \
            -R force-app/main/default/apex-ruleset.xml \
            -f text \
            -r reports/pmd-report.txt || true

      - name: Upload PMD Report
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: reports/pmd-report.txt
