name: Validate Production Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'force-app/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Install Salesforce Scanner Plugin
        run: sf plugins install @salesforce/sfdx-scanner

     - name: Run SFDX scanner on code
  run: |
    mkdir -p ${{ github.workspace }}/dist
    sf scanner:run \
      --format json \
      --target 'force-app/main/default/classes/**/*.cls' \
      --category "Design,Best Practices,Performance" \
      --outfile ${{ github.workspace }}/dist/ScanResults.json

      - name: Zip Salesforce Scanner Report
        run: |
          cd ${{ github.workspace }}/dist
          zip scanner-report.zip ScanResults.json
          cd ..

      - name: Upload Salesforce Scanner Report (Zipped JSON)
        uses: actions/upload-artifact@v4
        with:
          name: scanner-report
          path: dist/scanner-report.zip

      - name: Validate on our Org (Dry Run)
        uses: jawills/sf-deploy@v1.0
        with:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
          DRY_RUN: true
          TEST_LEVEL: NoTestRun
